Update advice.py
mypy --ignore-missing-imports kyu_5
kyu_5\find_the_safest_places_in_town\advice.py:74: error: Incompatible types in assignment (expression has type "Set[Any]", variable has type "List[Any]")
kyu_5\find_the_safest_places_in_town\advice.py:87: error: Argument 2 to "city_map_processing" has incompatible type "List[Any]"; expected "Set[Any]"
Found 2 errors in 1 file (checked 57 source files)