Run mypy kyu_4 --ignore-missing-imports --check-untyped-defs
kyu_4/permutations/permutations.py:9: error: Missing return statement  [return]
kyu_4/human_readable_duration_format/format_duration.py:52: error: Name "seconds" already defined on line 10  [no-redef]
kyu_4/strings_mix/solution.py:59: error: Name "results" already defined on line 50  [no-redef]
kyu_4/validate_sudoku_with_size/test_sudoku.py:169: error: Argument 1 to "Sudoku" has incompatible type "object"; expected "list[Any]"  [arg-type]
kyu_4/snail/test_snail.py:56: error: Need type annotation for "test_data"  [var-annotated]
kyu_4/most_frequently_used_words/test_top_3_words.py:51: error: Need type annotation for "test_data"  [var-annotated]
Found 6 errors in 6 files (checked 44 source files)